# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hsiang-Huang Wu
email: virtuoso.wu@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I have a predilection for the interdisciplinary research that includes parallel computing, computer vision
  and statistics. Besides my strong knowledge of hardware, I am adept at the implementations through
  understanding the math beyond the applications. That is, I am familiar with how the applications
  interact with the underlying hardware in a mathematically meaningful way. I believe that a better
  implementation is about knowing not how to do it but why to do it. The poise of the theoretic
  foundation and engineering realization is the quintessential part of my career. To promise it, I always
  stay open minded for any interesting idea and enjoy learning the incorporation of the different knowledge
  and techniques
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  dspcad

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
